### ISSUE TITLE
vortex command not found

### ISSUE THREAD

**Issue by abraham0477** [AlexsJones/vortex#15]
Hi,

I successfully cloned vortex located under (https://github.com/AlexsJones/vortex.git) so I can call it when run build_environment.sh under kubernetes-zookeeper cluster repo (https://github.com/AlexsJones/kubernetes-zookeeper-cluster.git) 

The command failed saying "vortex command not found". Am I missing something? When I changed cloned directory vortex, I don't see any executable file referred to vortex!

Below is how the sh file looks like which throwing this error:

#! /bin/bash
#################################################################################
#     File Name           :     build_environment.sh
#     Created By          :     jonesax
#     Creation Date       :     [2017-09-26 21:26]
#     Last Modified       :     [2018-05-22 17:46]
#     Description         :
#################################################################################

echo "Building for environment $1"

rm -rf deployment || true

vortex --template templates --output deployment -varpath ./environments/$1.yaml

**Comment by AlexsJones** [comment]
Hey, @abraham0477 

Vortex is a golang program. 

You'll need golang installed [guide here](https://golang.org/doc/install#install)

When you have golang installed you can run `go get github.com/AlexsJones/vortex` and as long as you've added $GOPATH/bin to your $PATH it will just work via `vortex`

Thanks!

**Comment by abraham0477** [comment]
Thank you so much Alex for your quick response. I got Golang installed and it can see vortex now but I'm running into a different issue as:

Building for environment small.yaml
WARN[0000] Unable to load variables due to./environments/small.yaml.yaml is not a valid path any idea?

Just fyi, here is the list of files & dirs of the path where the build env runs from:
build_environment.sh  environments  README.md  templates

& the command that use to run is: ./build_environment.sh small.yaml

**Comment by abraham0477** [comment]
I got the path fixed and I'm good to go to close this ticket. Thanks @AlexsJones again for your help here.
